### ISSUE TITLE
메인페이지 세부 css

### ISSUE THREAD

**Issue by JaeHeon-Kim** [codestates/whywine-client#110]
### ISSUE
- Group:  client
- Type: css
- Detail: 메인페이지 전반적인 css작업 진행
- 
### TODO
1. [x] 탭 기능 구현
2. [x] 태그 컨테이너 와인 컨테이너 그리드 맞추기
3. [x] 헤더 검색 수정
4. [x] 데이터가 렌더되지 않은 경우 그에 맞는 이미지 업로드

### LABEL
E: 6h
bare minimum
