### ISSUE TITLE
검색시 새로운 페이지로 이동 후 검색 결과 렌더

### ISSUE THREAD

**Issue by JaeHeon-Kim** [codestates/whywine-client#120]
### ISSUE
- Group:  client
- Type: feature
- Detail: 검색결과 페이지 생성, 검색시 검새 결과를 새로운 페이지에 렌더

### TODO
1. [ ] 검색 페이지 생성
2. [ ] 검색시 페이지 이동
3. [ ] 검색 결과 검색 페이지 렌더

### LABEL
E: 3h
bare minimum
