### ISSUE TITLE
와인 별점 평균

### ISSUE THREAD

**Issue by JaeHeon-Kim** [codestates/whywine-client#152]
### ISSUE
- Group:  client
- Type:  feature
- Detail:  와인 별점 평균을 서버에서 받아와 메인페이지 와인 카드에 렌더

### TODO
1. [x] 서버에서 와인 별점 평균 받아오기
2. [x] 평균 와인 카드에 렌더
3. [x] 별점 UI적으로 표현

### LABEL
E: 2h
bare minimum
