### ISSUE TITLE
Survey 진입 전 모달창 구현

### ISSUE THREAD

**Issue by NoelYoon96** [codestates/whywine-client#41]
### ISSUE
- Group:  client
- Type: feature
- Detail: 모달창 구현

### TODO
1. [x] 와인 추천 받아보시겠습니까? 안내문
2. [x] 메인페이지 이동 버튼 
3. [x] 설문조사 이동 버튼

### LABEL
E: 1h
bare minimum
