### ISSUE TITLE
Main 태그 업데이트

### ISSUE THREAD

**Issue by JaeHeon-Kim** [codestates/whywine-client#74]
### ISSUE
- Group:  client
- Type: feature
- Detail: 메인페이지 태그를 선택시 서버에 요청하여 와인 컨테이너를 리랜더링

### TODO
1. [ ] 태그 선택시 서버와 통신
2. [x] 태그 업데이트 시 리랜더링
3. [x] 태그 목록 컨테이너 제작
4. [x] 태그 슬라이더 제작

### LABEL
E: 6h
bare minimum
